name: KbFFA
version: '${project.version}'
main: me.darux.kbffa.Main
authors: [ D4RUX ]
description: Core of KnockBackFFA
website: https://daruxdev.es
softdepend:
  - HolographicDisplays
commands:
  arena:
  kbffa:
  suicide:
  playtime:
